let products = [
  {
    id: "1",
    name: "Camera Nikon",
    price: 200,
    img: "images/Nicon_2.jpg",
    img2: "images/Nicon_1.jpg",
    img3: "images/Nicon_3.jpg",
    inCart: 0,
    categories: "camera",
    color: "black",
    avallability: "true",
    quantity: "5",
    size: "null",
    sku: "0000-0-1",
  },
  {
    id: "2",
    name: "Laptop Lenovo V15",
    price: 2500,
    img: "images/lenovoV15_1.jpg",
    img2: "images/lenovoV15_2.jpg",
    img3: "images/lenovoV15_3.jpg",
    inCart: 0,
    categories: "laptop",
    color: "black",
    avallability: "true",
    quantity: "5",
    size: "null",
    sku: "0000-0-2",
  },
  {
    id: "3",
    name: "Pad X-box",
    price: 100,
    img: "images/pad-xbox_2.jpg",
    img2: "images/pad-xbox.jpg",
    img3: "images/6456332_sd 1.svg",
    inCart: 0,
    categories: "accesories",
    color: "black",
    avallability: "true",
    quantity: "5",
    size: "null",
    sku: "0000-0-3",
  },
  {
    id: "4",
    name: "Headphones JBL",
    price: 50,
    img: "images/headphones_Jbl_1.jpg",
    img2: "images/headphones_Jbl_2.jpg",
    img3: "images/headphones_Jbl_3.jpg",
    inCart: 0,
    categories: "accesories",
    color: "black",
    avallability: "true",
    quantity: "5",
    size: "null",
    sku: "0000-0-4",
  },
  {
    id: "5",
    name: "Pad PS5",
    price: 100,
    img: "images/Pad_PS5_1.jpg",
    img2: "images/Pad_PS5_2.jpg",
    img3: "images/Pad_PS5_3.jpg",
    inCart: 0,
    categories: "accesories",
    color: "black",
    avallability: "true",
    quantity: "5",
    size: "null",
    sku: "0000-0-5",
  },
  {
    id: "6",
    name: "Laptop Lenovo",
    price: 2500,
    img: "images/lenovo_gaming_3.jpg",
    img2: "images/lenovo_gaming_1.jpg",
    img3: "images/lenovo_gaming_2.jpg",
    inCart: 0,
    categories: "laptop",
    color: "black",
    avallability: "true",
    quantity: "5",
    size: "null",
    sku: "0000-0-6",
  },
  {
    id: "7",
    name: "Camera Canon",
    price: 200,
    img: "images/Camera_Canon_1.jpg",
    img2: "images/Camera_Canon_2.jpg",
    img3: "images/Camera_Canon_3.jpg",
    inCart: 0,
    categories: "camera",
    color: "black",
    avallability: "true",
    quantity: "5",
    size: "null",
    sku: "0000-0-7",
  },
  {
    id: "8",
    name: "Headphones Sony",
    price: 50,
    img: "images/headphones_Sony_1.jpg",
    img2: "images/headphones_Sony_2.jpg",
    img3: "images/headphones_Sony_3.jpg",
    inCart: 0,
    categories: "accesories",
    color: "black",
    avallability: "true",
    quantity: "5",
    size: "null",
    sku: "0000-0-8",
  },
];
