let products = [
  {
    id: "1",
    name: "Camera Nikon",
    price: 200,
    img: "images/camera 1.svg",
    inCart: 0,
    categories: "camera",
  },
  {
    id: "2",
    name: "Laptop Lenovo",
    price: 2500,
    img: "images/Frame 29 (2).svg",
    inCart: 0,
    categories: "laptop",
  },
  {
    id: "3",
    name: "Pad X-box",
    price: 100,
    img: "images/Frame 29 (1).svg",
    inCart: 0,
    categories: "accesories",
  },
  {
    id: "4",
    name: "Headphones",
    price: 50,
    img: "images/Frame 29.svg",
    inCart: 0,
    categories: "accesories",
  },
  {
    id: "5",
    name: "Pad X-box",
    price: 100,
    img: "images/Frame 29 (1).svg",
    inCart: 0,
    categories: "accesories",
  },
  {
    id: "6",
    name: "Laptop Lenovo",
    price: 2500,
    img: "images/Frame 29 (2).svg",
    inCart: 0,
    categories: "laptop",
  },
  {
    id: "7",
    name: "Camera Canon",
    price: 200,
    img: "images/camera 1.svg",
    inCart: 0,
    categories: "camera",
  },
  {
    id: "8",
    name: "Headphones",
    price: 50,
    img: "images/Frame 29.svg",
    inCart: 0,
    categories: "accesories",
  },
];
