let products = [
  {
    id: "1",
    name: "Camera Nikon",
    price: 200,
    img: "images/camera 1.svg",
    inCart: 0,
    categories: "camera",
    color: "black",
    avallability: "true",
    quantity: "5",
    size: "null",
    sku: "0000-0-1",
  },
  {
    id: "2",
    name: "Laptop Lenovo",
    price: 2500,
    img: "images/Frame 29 (2).svg",
    inCart: 0,
    categories: "laptop",
    color: "black",
    avallability: "true",
    quantity: "5",
    size: "null",
    sku: "0000-0-2",
  },
  {
    id: "3",
    name: "Pad X-box",
    price: 100,
    img: "images/Frame 29 (1).svg",
    inCart: 0,
    categories: "accesories",
    color: "black",
    avallability: "true",
    quantity: "5",
    size: "null",
    sku: "0000-0-3",
  },
  {
    id: "4",
    name: "Headphones",
    price: 50,
    img: "images/Frame 29.svg",
    inCart: 0,
    categories: "accesories",
    color: "black",
    avallability: "true",
    quantity: "5",
    size: "null",
    sku: "0000-0-4",
  },
  {
    id: "5",
    name: "Pad X-box",
    price: 100,
    img: "images/Frame 29 (1).svg",
    inCart: 0,
    categories: "accesories",
    color: "black",
    avallability: "true",
    quantity: "5",
    size: "null",
    sku: "0000-0-5",
  },
  {
    id: "6",
    name: "Laptop Lenovo",
    price: 2500,
    img: "images/Frame 29 (2).svg",
    inCart: 0,
    categories: "laptop",
    color: "black",
    avallability: "true",
    quantity: "5",
    size: "null",
    sku: "0000-0-6",
  },
  {
    id: "7",
    name: "Camera Canon",
    price: 200,
    img: "images/camera 1.svg",
    inCart: 0,
    categories: "camera",
    color: "black",
    avallability: "true",
    quantity: "5",
    size: "null",
    sku: "0000-0-7",
  },
  {
    id: "8",
    name: "Headphones",
    price: 50,
    img: "images/Frame 29.svg",
    inCart: 0,
    categories: "accesories",
    color: "black",
    avallability: "true",
    quantity: "5",
    size: "null",
    sku: "0000-0-8",
  },
];
